# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreprenda', models.CharField(max_length=400)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('mensaje', models.CharField(max_length=400)),
            ],
        ),
    ]
